CFLAGS=-Wall -g

TARGET=ex
TARGET_MARTIN=$(TARGET)_martin
SRC=$(TARGET).c
SRC_MARTIN=$(TARGET_MARTIN).c
ARGS=test

build:
	gcc $(CFLAGS) $(SRC) -o $(TARGET)

build-martin:
	gcc $(CFLAGS) $(SRC_MARTIN) -o $(TARGET_MARTIN)

run: build 
	./$(TARGET) $(ARGS)

run-martin: build-martin
	./$(TARGET_MARTIN) $(ARGS)
